source 'https://rubygems.org'

gem 'bootstrap-sass', '~> 3.1.1'
gem 'bootstrap_helper'
gem 'coffee-rails', '~> 4.0.0'
gem 'figaro'
gem 'font-awesome-rails'
gem 'github_api'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '4.0.3'
gem 'sass-rails', '~> 4.0.0'
gem 'therubyracer'
gem 'uglifier', '>= 1.3.0'
